### ISSUE TITLE
How to trigger only when uploaded to a specific bucket? 

### ISSUE THREAD

**Issue by AdithyanI** [meteatamel/cloudrun-tutorial#35]
Currently, I try to do it from the cloud run UI with the full resource name of the bucket, like so : 

![image](https://user-images.githubusercontent.com/12037164/103356488-4b6c7d00-4ab1-11eb-86e3-b9d353857e87.png)

But, it does not work and the event does not get triggered.

**Comment by meteatamel** [comment]
Sorry for the delay in responding. This is not possible right now as resource name in the AuditLog includes the file name as well, so it won't match. Your only option is to leave out the resource name and receive events from all buckets. Then, in your code, you need to filter out events from buckets you're not interesting in. In the future release of Eventarc, you'll have ability to filter better.
